project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
    right: 
      - icon: github
        menu:
          - text: Website Source Code
            url:  https://github.com/ethanmwarren/personal-website
          - text: Github Profile
            url:  https://github.com/ethanmwarren
  page-footer:
    right: "&copy; 2024, Ethan Warren"
#  comments:
#    utterances:
#      repo: ethanmwarren/personal-website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute: 
  freeze: auto



